spring.application.name=API-GATEWAY
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8081/eureka/

spring.cloud.gateway.mvc.websocket.enabled=true


spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST