spring.application.name=ws-service

server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8081/eureka/
eureka.client.register_with_eureka=true
eureka.client.fetch_registry=true
eureka.instance.prefer_ip_address=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
