spring.application.name=ws-service

server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8081/eureka/
eureka.client.register_with_eureka=true
eureka.client.fetch_registry=true
eureka.instance.prefer_ip_address=true

